export const BUSINESSES_FETCH_STARTED = "BUSINESSES_FETCH_STARTED";
export const BUSINESSES_RETRIVED = "BUSINESSES_RETRIVED";
export const BUSINESSES_CREATED = "BUSINESSES_CREATED";
export const BUSINESSES_UPDATED = "BUSINESSES_UPDATED";
export const BUSINESSES_DELETED = "BUSINESSES_DELETED";
